---
# Install golang packages

- name: Install golang tools
  ansible.builtin.command: go install
  args:
    chdir: "{{ item.path }}"
  loop: "{{ go_tools }}"
  loop_control:
    label: "{{ item.path }}"
