# roles/common/main.yml
---
- name: import vars
  ansible.builtin.include_vars: ../../group_vars/kali/main.yml

- name: Full Upgrade
  become: True
  ansible.builtin.import_tasks: update.yml

- name: Fix /etc/sudoers
  become: True
  ansible.builtin.import_tasks: sudo.yml
  
- name: apt Tasks
  become: True
  ansible.builtin.import_tasks: apt.yml

# TODO: Add OhMyZsh and PowerLevel10k
- name: Set Environment Variables in .zshrc file
  become: True
  ansible.builtin.import_tasks: env.yml

- name: Python Packages
  ansible.builtin.import_tasks: pip.yml

- name: Install Tools from GitHub
  become: True
  ansible.builtin.import_tasks: git.yml

- name: Install GitHub Binary Tools
  become: True
  ansible.builtin.import_tasks: github.yml

- name: Install golang Tools
  become: True
  ansible.builtin.import_tasks: golang.yml

- name: Install GitHub CLI Client
  become: True
  ansible.builtin.import_tasks: gh-cli.yml

- name: Configure ZSH Environment
  become: True
  ansible.builtin.import_tasks: zsh-env.yml
