---
#- name: Install required packages
#  apt:
#    name:
#      - apt-transport-https
#      #- software-properties-common
#    state: present

#- name: Import GitHub CLI GPG key
#  ansible.builtin.apt_key:
#    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
#    state: present
- name: Add an apt key for gh cli from a keyserver
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: C99B11DEB97541F0

#- name: Add GitHub CLI repository
#  ansible.builtin.apt_repository:
#    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
#    state: present
#    filename: "github-cli"
- name: Add gh cli repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://cli.github.com/packages focal main
    state: present

#- name: Update APT package index
#  ansible.builtin.apt:
#    update_cache: yes

#- name: Install GitHub CLI
#  apt:
#    name: gh
#    state: present
- name: Ensure gh is at the latest version
  ansible.builtin.apt:
    name: gh
    state: latest