---
- name: Download GitHub releases for multiple repositories
  block:
    - name: Ensure the script is deployed to the target system
      copy:
        src: "{{ role_path }}/files/github-slurp.sh"
        dest: /usr/local/bin/github-slurp.sh
        mode: '0755'

    - name: Extract owner and repo and execute script
      command: >
        /usr/local/bin/github-slurp.sh "{{ owner }}" "{{ repository }}"
      vars:
        owner: "{{ item.repo.split('/')[0] }}"
        repository: "{{ item.repo.split('/')[1] }}"
      loop: "{{ common_binary_packages }}"
      loop_control:
        label: "{{ item.repo }}"

