---
- name: Setup go install environment
  block:
    - name: Set GOBIN environment variable in zsh
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export GOBIN={{ ansible_env.HOME }}/go/bin'
        state: present

    - name: Ensure GOBIN is in PATH for zsh
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH=$PATH:{{ ansible_env.HOME }}/go/bin'
        state: present
      notify: Reload zsh environment

    - name: Install golang tools
      ansible.builtin.command:
        cmd: go install "{{ item.repo }}"
      loop: "{{ common_go_tools }}"
      loop_control:
        label: "{{ item.tool }}"