# roles/common/main.yml
---
- name: apt tasks
  become: True
  ansible.builtin.import_tasks: apt.yml

- name: Set Environment Variables in .zshrc file
  become: True
  ansible.builtin.import_tasks: env.yml

- name: Python Packages
  ansible.builtin.import_tasks: pip.yml

- name: Install Tools from GitHub
  become: True
  ansible.builtin.import_tasks: git.yml

- name: Install Binary Packages
  become: True
  ansible.builtin.import_tasks: binaries.yml
