# roles/common/main.yml
---
- name: import vars
  ansible.builtin.include_vars: ../../group_vars/kali/main.yml

- name: GitHub Binary Downloads
  become: True
  ansible.builtin.import_tasks: github.yml

- name: Fix /etc/sudoers
  become: True
  ansible.builtin.import_tasks: sudo.yml
  
- name: apt tasks
  become: True
  ansible.builtin.import_tasks: apt.yml

- name: Set Environment Variables in .zshrc file
  become: True
  ansible.builtin.import_tasks: env.yml



- name: Python Packages
  ansible.builtin.import_tasks: pip.yml

- name: Install Tools from GitHub
  become: True
  ansible.builtin.import_tasks: git.yml

- name: Install Binary Packages
  become: True
  ansible.builtin.import_tasks: binaries.yml

- name: Customize QTerminal
  become: False
  ansible.builtin.import_tasks: qterminal.yml

- name: Install VSCode
  become: True
  ansible.builtin.import_tasks: vscode.yml