# roles/common/main.yml
---
- name: import vars
  ansible.builtin.include_vars: ../../group_vars/kali/main.yml

#- name: Disable Screen Lock
#  become: True
#  ansible.builtin.import_tasks: screenlock.yml

- name: Full Upgrade
  become: True
  ansible.builtin.import_tasks: update.yml

- name: Fix /etc/sudoers
  become: True
  ansible.builtin.import_tasks: sudo.yml

- name: Fix /etc/needrestart/notify.conf
  become: True
  ansible.builtin.import_tasks: notifyd-disable.yml
  
- name: apt Tasks
  become: True
  ansible.builtin.import_tasks: apt.yml

# TODO: Add OhMyZsh and PowerLevel10k
- name: Set Environment Variables in .zshrc file
  become: True
  ansible.builtin.import_tasks: env.yml

- name: Python Packages
  ansible.builtin.import_tasks: pip.yml

- name: Install Tools from GitHub
  become: True
  ansible.builtin.import_tasks: git.yml

- name: Install GitHub Binary Tools
  become: True
  ansible.builtin.import_tasks: github2.yml

- name: Install golang Tools
  become: False
  ansible.builtin.import_tasks: golang.yml

- name: Customize QTerminal
  become: False
  ansible.builtin.import_tasks: qterminal.yml

- name: Install and Configure VSCode
  become: True
  ansible.builtin.import_tasks: vscode.yml

- name: Install GitHub CLI Client
  become: True
  ansible.builtin.import_tasks: gh-cli.yml

#- name: Install Obsidian
#  become: True
#  ansible.builtin.import_tasks: obsidian.yml

- name: Restore xfce4 panel
  become: false
  ansible.builtin.import_tasks: xfce4-panel.yml

- name: Configure ZSH Environment
  become: True
  ansible.builtin.import_tasks: zsh-env.yml

- name: Set display resolution on XFCE4
  become: True
  ansible.builtin.import_tasks: xfce-res.yml

- name: Fix Perms
  become: True
  ansible.builtin.import_tasks: fix-perms.yml
