---
- name: Install pipx packages
  become_user: "{{ kali_user }}"
  community.general.pipx:
    name: "{{ item }}"
    #state: latest
    executable: pipx
    install_deps: true
  loop: "{{ common_pipx_packages }}"

- name: Install Remote pipx packages
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
    global: true
    #executable: python3
  loop: "{{ common_remotepipx_packages }}"

- name: Run pipx ensurepath and completions
  become_user: "{{ kali_user }}"
  ansible.builtin.shell: pipx ensurepath && pipx completions
  args:
    executable: /bin/zsh
