---
- name: Install pipx packages
  become_user: "{{ kali_user }}"
  community.general.pipx:
    name: "{{ item }}"
    install_deps: true
    global: false
  loop: "{{ common_pipx_packages }}"

- name: Install Remote pipx packages
  become_user: "{{ kali_user }}"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    global: false
  loop: "{{ common_remotepipx_packages }}"

- name: Run pipx ensurepath and completions
  become_user: "{{ kali_user }}"
  ansible.builtin.shell: pipx ensurepath && pipx completions
  args:
    executable: /bin/zsh
