- name: Install and upgrade pip
  ansible.builtin.pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Install python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  loop: "{{ pip_packages }}"

#- name: Install pipx
#  ansible.builtin.shell: python3 -m pip install --user pipx

# Broken, pyyaml needs to be less than 6.0.0, 6.0.1 gets installed
#- name: Source Path and Download pipx
#  become_user: "{{ zsh_user }}"
#  ansible.builtin.shell: source .zshrc && pipx install witnessme --force
#  #ansible.builtin.shell: pipx install witnessme --force
#  args:
#    executable: /bin/zsh

#- name: Source Path and Download pipx
#  become_user: "{{ zsh_user }}"
#  ansible.builtin.shell: source .zshrc && pipx install crackmapexec --force
#  args:
#    executable: /bin/zsh
