#- name: Install and upgrade pip
#  ansible.builtin.pip:
#    name: pip
#    extra_args: --upgrade
#    executable: pip3

#- name: Install python pip packages
#  become_user: "{{ zsh_user }}"
#  ansible.builtin.pip:
#    name: "{{ item }}"
#    state: latest
#    executable: pip3
#  loop: "{{ common_pip_packages }}"

- name: Install pipx packages
  become_user: "{{ zsh_user }}"
  community.general.pipx:
    name: "{{ item }}"
    #state: latest
    #executable: pipx
    cmd: "pipx install {{ item }} --include-deps"
  loop: "{{ common_pipx_packages }}"

- name: Install Remote pipx packages
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
    #executable: python3
  loop: "{{ common_remotepipx_packages }}"

- name: Run pipx ensurepath and completions
  become_user: "{{ zsh_user }}"
  ansible.builtin.shell: pipx ensurepath && pipx completions
  args:
    executable: /bin/zsh
