---
- name: Update QTerminal Settings
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"
    backup: yes
    block: |
      [General]
      AskOnExit=true
      Borderless=false
      FixedTabWidth=true
      FixedTabWidthValue=500
      HideTabBarWithOneTab=false
      HistoryLimited=false
      OpenNewTabRightToActiveTab=false
      SavePosOnExit=true
      SaveSizeOnExit=true
      TabBarless=false
      UseCWD=true
      fontFamily=MesloLGS NF
      fontSize=12
      highlightCurrentTerminal=true
      showTerminalSizeHint=true
