- name: Include gantsign.visual-studio-code role
  ansible.builtin.include_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username: "{{ ansible_user_id }}" 
        visual_studio_code_extensions:
          - IronGeek.vscode-env
          - Tyriar.sort-lines
          - donjayamanne.githistory
          - eamodio.gitlens
          - esbenp.prettier-vscode
          - foxundermoon.shell-format
          - junstyle.php-cs-fixer
          - marduc812.nmap-peek
          - mechatroner.rainbow-csv
          - mhutchie.git-graph
          - ms-python.python
          - ms-python.vscode-pylance
          - ms-vscode.cpptools
          - ms-vscode.powershell
          - redhat.ansible
          - redhat.vscode-yaml
          - shakram02.bash-beautify
          - wesbos.theme-cobalt2
          - xshrim.txt-syntax
          - zobo.php-intellisense