---
- name: Set display resolution on XFCE4
  block:
    - name: Check available displays and resolutions
      command: xrandr
      register: xrandr_output

    - name: Set display resolution
      command: xrandr --output Virtual1 --mode 2560x1600
      args:
        creates: "/home/{{ kali_user }}/.config/autostart/set-resolution.desktop"
      when: "'2560x1600' in xrandr_output.stdout"

    - name: Create the directory if it does not exist
      ansible.builtin.file:
        path: "/home/{{ kali_user }}/.config/autostart"
        state: directory
        owner: "{{ kali_user }}"
        group: "{{ kali_user }}"
        mode: 0755
    
    - name: Make resolution persistent by creating an autostart file
      copy:
        dest: "/home/{{ kali_user }}/.config/autostart/set-resolution.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Exec=xrandr --output Virtual1 --mode 2560x1600
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name[en_US]=Set Resolution
          Name=Set Resolution
          Comment[en_US]=Sets the display resolution on startup
          Comment=Sets the display resolution on startup
        owner: "{{ kali_user }}"
        group: "{{ kali_user }}"
        mode: 0755
