---
- name: Setup zsh Environment
  block:
  
  - name: Include gantsign.oh-my-zsh role
    ansible.builtin.include_role:
      name: gantsign.oh-my-zsh
    vars:
      users:
        - username: "{{ zsh_user }}"
  
  - name: Edit .zshrc
    copy:
      src: "{{ role_path }}/files/zshrc"
      dest: "{{ ansible_env.HOME }}/.zshrc"
      mode: '0644'
  
  
#  - name: Install and configure zsh plugins


# Install Fonts
  - name: Ensure download directory exists
    file:
      path: "{{ ansible_env.HOME }}/.fonts"
      state: directory
  
  - name: Download multiple files from URLs
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
      owner: "{{ kali_user }}"
      group: "{{ kali_user }}"
      mode: 0644
    loop: "{{ font_urls }}"

# Install PowerLevel10k
  - name: Check if the repository directory exists
    ansible.builtin.stat:
      path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    register: repo_dir
  
  - name: Clone the repository if it does not exist
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
      clone: yes
      update: no
    when: not repo_dir.stat.exists

  - name: Pull the latest changes if the repository exists
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
      update: yes
    when: repo_dir.stat.exists

  - name: Configure PowerLevel10k
    copy:
      src: "{{ role_path }}/files/p10k.zsh"
      dest: "{{ ansible_env.HOME }}/.p10k.zsh"
      mode: 0644
  
  
  




  

  